version: '2.1'
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.50.18.0/24
        gateway: 10.50.18.254

services:
########
  php7_nginx:
#    image: php:7-fpm
    container_name: ${DOMAIN_NAME}_php7_nginx
    hostname: ${DOMAIN_NAME}
    build:
      context: ./php7-fpm
      dockerfile: Dockerfile
    volumes_from:
      - froxlor-data
    depends_on:
      - froxlor-data
      - sql
    restart: always
    networks:
      app_net:
        ipv4_address: 10.50.18.1
    ports:
      -  "${HTTP_IP}:${HTTP_PORT}:80"
      -  "${HTTP_IP}:${HTTPS_PORT}:443"
      -  "${HTTP_IP}:${PORT_SFTP}:21"
      -  "${HTTP_IP}:${BAREOSFD_PORT}:9102"

########
  sql:
    image: mariadb:10.2
    container_name: ${DOMAIN_NAME}_sql
    hostname: froxlor_sql
    volumes_from:
      - froxlor-data
    depends_on:
      - froxlor-data
    restart: always
    env_file:
      - ./.env
    networks:
      app_net:
        ipv4_address: 10.50.18.3

########
  froxlor-data:
    image: busybox
    container_name: ${DOMAIN_NAME}_data
    hostname: froxlor_data
    networks:
      app_net:
        ipv4_address: 10.50.18.2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "${DATA_PATH}/mariadb-data:/var/lib/mysql"
      - "${DATA_PATH}/acme.sh/:/root/.acme.sh/"
      - "${DATA_PATH}/ssl/:/etc/ssl/froxlor/"
      - "${DATA_PATH}/customers:/var/customers"
      - "${DATA_PATH}/froxlor:/var/www/froxlor"
      - "${DATA_PATH}/nginx/conf.d/:/etc/nginx/conf.d/"
      - "${DATA_PATH}/apache2/conf-enabled/:/etc/apache2/conf-enabled/"
      - "${DATA_PATH}/nginx/sites-enabled/:/etc/nginx/sites-enabled/"

